include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    constant_identifier_names: ignore
    prefer_interpolation_to_compose_strings: ignore
    use_function_type_syntax_for_parameters: ignore

linter:
  rules:
    prefer_const_constructors: false
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
    prefer_const_literals_to_create_immutables: false