name: fintech_app
description: ""
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  path: ^1.9.0
  get_it: ^8.0.3
  provider: ^6.1.2
  equatable: ^2.0.7
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  audioplayers: ^6.1.2
  firebase_auth: ^5.5.1
  path_provider: ^2.1.5
  firebase_core: ^3.12.1
  mobile_scanner: ^6.0.7
  google_sign_in: ^6.3.0
  cupertino_icons: ^1.0.8
  firebase_database: ^11.3.4
  shared_preferences: ^2.5.2
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
  assets:
    - 'assets/drums.mp3'
    - 'assets/onboarding.png'