name: clearpay
description: ""
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  path: ^1.9.0
  get_it: ^8.0.3
  mockito: ^5.4.5
  provider: ^6.1.2
  equatable: ^2.0.7
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  audioplayers: ^6.1.2
  path_provider: ^2.1.5
  firebase_auth: ^5.5.3
  mobile_scanner: ^6.0.7
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.7
  contacts_service: ^0.6.3
  shared_preferences: ^2.5.2
  font_awesome_flutter: ^10.8.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.8
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
  assets:
    - 'assets/assistant.mp3'
    - 'assets/onboarding.png'